name: convert

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Path
        run: pwd

      - name: Converting index.adoc
        run: rm index.html && asciidoctor index.adoc
        
      - name: Converting apoll/index.adoc
        run: cd apoll/ && asciidoctor && rm index.html && asciidoctor index.adoc
      
      - name: Converting mose/index.adoc
        run: cd mose/ && asciidoctor && rm index.html && asciidoctor index.adoc
